mcir:
  # set this to true to get debug output.
  # you can enable debug output at any time by passing --debug
  debug: false

  # the default instance if none is given and none could have been guessed.
  default_instance: localbukkit

  # If set to true mcir will try to autocomplete instance names.
  # (the dot acts as filter chain)
  #   'gm' would match 'gmain'
  # When the input is ambiguous it will fail with a list of matched entries.
  instance_autocomplete: true

  # If set to true mcir will try to guess the instance from your current working directory.
  # This guessing only takes place if you don't pass an instance name.
  instance_cwd_guessing: true

  # java executable (might be java or java.exe)
  java_exe: java

  # will always be used unless `skip_java_args: true` is set
  java_args: -server

instance_defaults: &default_instance
  executable: minecraft_server.jar nogui
  skip_java_args: false
  java_args: -Xms1048M -Xmx2048M

  # You propably won't need to edit these...
  server_log: server.log
  server_plist: server.properties

  # Change this to `end' for BungeeCord instances
  stop_command: stop

# ==============================
# = Define your instances here =
# ==============================
# You should inherit from the default instance.
# Just look at the examples.
instances:
  # this one is just for rspec testing
  rspec:
    <<: *default_instance
    home: "%MCIR_ROOT%/spec/server"

  localbukkit:
    <<: *default_instance
    home: /Users/chaos/Library/Application Support/minecraft/_bukkit
    screen_name: mcir_localbukkit # is the default
    executable: craftbukkit.jar
    java_args: -Xms100M -Xmx512M

  geekya_main:
    <<: *default_instance
    home: /home/geekyamc/_main
    screen_name: mcir_geekya_main # you get the idea?
    executable: craftbukkit.jar
    java_args: -Xms2048M -Xmx10240M
