mcir:
  # set this to true to get debug output.
  # you can enable debug output at any time by passing --debug
  debug: false

  # the default instance if none is given and none could have been guessed.
  default_instance: debian

  # If set to true mcir will try to autocomplete instance names.
  # (the dot acts as filter chain)
  #   'gm' would match 'gmain'
  # When the input is ambiguous it will fail with a list of matched entries.
  instance_autocomplete: true

  # If set to true mcir will try to guess the instance from your current working directory.
  # This guessing only takes place if you don't pass an instance name.
  instance_cwd_guessing: true

  # vmrun executable (propably no need to change)
  vmrun: vmrun

instance_defaults: &default_instance
  type: player # ws|server|server1|fusion|esx|vc|player


# ==============================
# = Define your instances here =
# ==============================
# You should inherit from the default instance.
# Just look at the examples.
instances:
  debian:
    <<: *default_instance
    name: debian # set to match <home>/<name>.vmx (defaults to instance name and can be omitted if equal)
    home: /root/vmware/debian

    # Guest authentication
    # required for several commands (like screenCapture)
    guser: root
    gpass: foobar
